namespace Autogenerated_TestData.DataStructures;

public class Course(string name, int capacity, List<Person> students)
{
    public string Name { get; init; } = name;
    public int Capacity { get; init; } = capacity;
    public IEnumerable<Person> Students { get; init; } = students;

    public int Available => Capacity - Students.Count();

    public IEnumerable<Person> Seniors => Students.Where(s => s.BirthDate.Year < DateTime.Now.Year - 65);
}