using Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.ObjectModel;

namespace Autogenerated_TestData;

public class Course(string name, int capacity, List<Person> students)
{
    public string Name { get; init; } = name;
    public int Capacity { get; init; } = capacity;
    public IEnumerable<Person> Students { get; init; } = students;

    public int Available => Capacity - Students.Count();
}