namespace Autogenerated_TestData;

public class Person(string firstName, string lastName, DateTime birthDate, Guid id)
{
    public Guid Id { get; set; } = id;
    public string FirstName { get; set; } = firstName;
    public string LastName { get; set; } = lastName;
    public DateTime BirthDate { get; set; } = birthDate;
    // and tons of other properties

    public string FullName => $"{FirstName} {LastName}";
}