using AutoFixture;
using Autogenerated_TestData.DataStructures;

namespace Autogenerated_TestData;

public class InitializeCollectionsTests
{
    [Test]
    public void Test2()
    {
        var students = new List<Person>()
        {
            new ("Karel", "Vokurka", DateTime.Today, Guid.NewGuid()),
            new ("Jan", "Veselý", DateTime.Today, Guid.NewGuid())
            // add more ...
        };
        var course = new Course("Math", 7, students);

        Assert.That(course.Available, Is.EqualTo(5));
    }

    [Test]
    public void Test2_Simplified()
    {
        var students = new Fixture().CreateMany<Person>(2).ToList();
        var course = new Course("Math", 7, students);

        Assert.That(course.Available, Is.EqualTo(5));
    }

    [Test]
    public void Test2_Simplified2()
    {
        var fixture = new Fixture();
        var course = fixture.Build<Course>()
            .With(c => c.Capacity, 7)
            .With(c => c.Students, fixture.CreateMany<Person>(2).ToList())
            .Create();

        Assert.That(course.Available, Is.EqualTo(5));
    }
}