using AutoFixture;
using AutoFixture.AutoMoq;
using Autogenerated_TestData.DataStructures;
using Moq;

namespace Autogenerated_TestData;

public class MockingTests
{
    [Test]
    public void Test5()
    {
        var schoolMock = new Mock<ISchool>();
        var libraryMock = new Mock<ILibrary>();
        var restaurantMock = new Mock<IRestaurant>();
        // Plenty of setups ...

        var campus = new Campus(schoolMock.Object, libraryMock.Object, restaurantMock.Object);

        Assert.That(campus.Library, Is.Not.Null);
    }

    [Test]
    public void Test5_WorkingWithMocks()
    {
        var fixture = new Fixture().Customize(new AutoMoqCustomization());
        var libraryMock = fixture.Freeze<Mock<ILibrary>>();
        var campus = fixture.Create<Campus>();

        Assert.That(campus.Library, Is.EqualTo(libraryMock.Object));
    }
}
